GA Data Science - Final Project
James Clark

Real estate value can be extremely subjective. Almost all single family and rental properties can be summed up based on some standard objective features - square footage, number of bedrooms and bathrooms, lot size, and so on. But, there are other features that may be attractive to potential purchasers that are not as easily quantifiable.

The goal of this analysis is to use the language used to describe the property listing to determine other feature of a property listing. Additionally, a value could be associated with these objective features.

Analysis will be done using a set of Trulia property listing data found on kaggle.com (https://www.kaggle.com/promptcloud/real-estate-data-from-trulia).

In [ ]:
! pip install stringcase

In [57]:
import pandas as pd
import stringcase
import re
from nltk.corpus import stopwords
from nltk.stem import LancasterStemmer
from sklearn.feature_extraction.text import CountVectorizer

%matplotlib

Using matplotlib backend: Qt5Agg

In [125]:
def drop_unused_columns(df: pd.DataFrame):
    #Drop unused columns
    columns_to_keep = {'description', 'price', 'sqr_ft', 'style', 'longitude', 'latitude', 'lot_size', 'beds', 'bath'}
    df.drop(columns = df.columns.difference(columns_to_keep), inplace = True)
    
    return df

def numerize_columns(df: pd.DataFrame):    
    for column in ['sqr_ft', 'price', 'lot_size']:
        df[column] = df[column].apply(lambda sqft: re.sub("[^\d.]+", "", str(sqft)) if pd.notnull(sqft) else sqft)
    
    return df

def remove_rows_with_empty_descriptions(df: pd.DataFrame):
    df.dropna(subset = ['description'], inplace = True)
    return df
    
def import_and_clean(filename: str):
    df = pd.read_csv(filename)    
    #Snake case columns    
    df.columns = [stringcase.snakecase(column.lower()) for column in df.columns]    
    df = drop_unused_columns(df)    
    
    #Numberize some columns - sqr_ft
    df = numerize_columns(df)
    
    #Clean na values
    df = remove_rows_with_empty_descriptions(df)
    
    #Clean description of stopwords, stem words
    
    return df

In [126]:
df = import_and_clean('data/home/sdf/marketing_sample_for_trulia_com-real_estate__20190901_20191031__30k_data.csv')
df.head()

,description,price,style,sqr_ft,longitude,latitude,lot_size,beds,bath
0,NEW CONSTRUCTION in the North Central Corrido...,895900,4 Beds / 4.5 Baths,3447,-112.081985,33.560055,7895,4.0,4.5
1,UPDATED EAST DALLAS HOME READY FOR MOVE-IN. H...,247000,3 Beds / 2 Baths,1767,-96.676250,32.829227,7877,3.0,2.0
2,This single-family home is located at 30 Hurl...,44900,3 Beds / 1 Bath,1232,-78.825190,42.913000,3510,3.0,1.0
3,"Beautiful semi detached, ranch type corner ho...",959000,3 Beds / 2 Baths,1417,-73.860170,40.722960,2598,3.0,2.0
4,"great investor opportunity!!! , beautiful stu...",83500,Studio / 1 Bath,440,-80.206314,25.937965,NaN,NaN,1.0

In [131]:
df[df.beds.isna()].head(50)

,description,price,style,sqr_ft,longitude,latitude,lot_size,beds,bath
4,"great investor opportunity!!! , beautiful stu...",83500,Studio / 1 Bath,440,-80.206314,25.937965,NaN,NaN,1.0
51,"Charming, front-facing studio overlooking pic...",534000,Studio / 1 Bath,410,-71.078480,42.353540,410,NaN,1.0
66,"South Side Slopes - Nice cleared lot, able to...",32900,NaN,1476,-79.968760,40.419426,5040,NaN,NaN
73,Investor opportunity! This property is being ...,165149,NaN,1672,-76.687730,39.252000,7500,NaN,2.0
83,Vacant lot near So. Pasadena in Monterey Hill...,325000,NaN,42288,-118.191700,34.114200,0.97,NaN,NaN
109,Bright and sunny duplex on an oversized lot a...,19900,NaN,2268,-87.926300,43.081432,6969,NaN,NaN
223,Completely remodeled elegant unit on the 11th...,299000,Studio / 1 Bath,490,-118.184616,33.768402,0.52,NaN,1.0
230,"Motivated Seller, Empty lot in close Distance...",49000,NaN,1548,-75.159960,39.989020,1146,NaN,NaN
265,This Duplex Rowhome is the perfect opportunit...,475000,NaN,1746,-75.165855,39.975178,1583,NaN,NaN
332,This property is no longer available to rent o...,137771,NaN,1920,-96.022554,36.091499,10367,NaN,3.0
376,Fantastic development opportunity in a rapidl...,625000,NaN,3036,-75.230660,39.997660,0.78,NaN,NaN
411,This property is no longer available to rent o...,124178,NaN,1144,-76.582541,39.294056,910,NaN,1.0
437,Major price REDUCTION. Submit all offers--Sha...,396990,Studio / 1 Bath,664,-118.348300,34.104310,0.74,NaN,1.0
446,Amazing opportunity to own in the heart of Gl...,325000,NaN,500,-112.204690,33.540764,7431,NaN,NaN
448,This lot/land is located at 4044 W Girard Ave...,79000,NaN,3048,-75.205800,39.973648,1886,NaN,NaN
456,"Rare chance: own a 12.28 acre, guard-gated lo...",200000,NaN,534900,-111.883850,33.864677,12.28,NaN,NaN
463,Duplex fully rented at $700 and $750 with mon...,200000,NaN,1440,-112.093300,33.438380,4175,NaN,NaN
509,**Please be discreet and do not disturb the o...,250000,NaN,1300,-83.004360,39.982162,NaN,NaN,NaN
565,Beautiful and cozy fully furnished studio wit...,258000,Studio / 1 Bath,449,-80.188210,25.774817,NaN,NaN,1.0
640,Investor opportunity! This property is being ...,,NaN,704,-82.932380,42.425674,4138,NaN,1.0
653,Large corner development deal in OPPORTUNITY ...,495000,NaN,5856,-75.207760,39.966240,2818,NaN,NaN
659,This single-family home is located at 127 Bla...,498000,Studio,3750,-73.914970,40.664974,1250,NaN,NaN
661,This multi-family home is located at 1039 E 2...,410000,NaN,1858,-73.854515,40.877937,2375,NaN,NaN
717,This unit is part of Austin's Affordable Hous...,175000,Studio / 1 Bath,407,-97.720665,30.283743,NaN,NaN,1.0
835,"$3700/month income, at a selling price of $18...",185000,NaN,1560,-75.141620,40.054764,1636,NaN,NaN
866,"The ultimate Marigny compound, this beautiful...",1295000,NaN,4066,-90.052550,29.964645,NaN,NaN,NaN
901,Development opportunity in North Central 15 x...,35000,NaN,1601,-75.162090,39.990467,1020,NaN,NaN
922,Presented for sale is Raw Land. DON'T bother ...,1595000,NaN,2352,-118.268135,34.050594,6219,NaN,NaN
937,"NEW TO MARKET. Live, work and play at the Les...",440000,Studio / 1 Bath,115020,-73.968170,40.757755,0.35,NaN,1.0
1054,Own It Now: Please visit buildingdetroit.org ...,1000,Studio / 1 Bath,1056,-83.089950,42.434880,2788,NaN,1.0
1105,Luxurious High Rise living at the Trump!! Spe...,249900,Studio / 1 Bath,534,-115.172640,36.129562,NaN,NaN,1.0
1130,Wide Flat lot in desirable neighborhood. Very...,5000,NaN,700,-85.810440,38.266136,5576,NaN,NaN
1423,Don't miss out on this cash flowing double. U...,74000,Studio / 2 Baths,1216,-83.065380,39.951610,3485,NaN,2.0
1452,This is your next best investment! Looking fo...,174900,NaN,2862,-83.118080,42.372970,3485,NaN,4.0
1460,This property is being sold with its sister p...,65000,NaN,864,-95.418410,29.852327,10000,NaN,NaN
1517,Commercial Zone C3 * 400' of great frontage *...,1500000,NaN,152900,-98.444620,29.606518,3.39,NaN,NaN
1530,8.81 acre tact by former Pac Ball field. Conv...,235000,NaN,385776,-89.963020,29.906988,8.81,NaN,NaN
1552,Great Opportunity for Investors or First-Time...,225000,NaN,1536,-75.134360,40.017563,1120,NaN,NaN
1568,"BEAUTIFUL view, mature trees, BUILD your DREA...",129000,NaN,41817,-98.475780,29.656939,0.96,NaN,NaN
1598,Beautifully appointed studio apartment availa...,329900,Studio / 1 Bath,506,-75.170425,39.949253,NaN,NaN,1.0
1644,"REDUCED OVER $250,000 9 Unit character buildi...",2995000,NaN,7384,-118.343254,34.077580,7502,NaN,NaN
1661,Large lot off of 22nd Avenue in Miami / North...,119000,NaN,625,-80.235110,25.864082,8250,NaN,NaN
1729,DEVELOPERS AND DREAMERS: This is the lot for ...,150000,NaN,174719,-98.433840,29.406073,4.01,NaN,NaN
1787,Excellent opportunity to own one of Washingto...,700000,NaN,1800,-77.021770,38.951252,221,NaN,NaN
1805,Coming soon. Brand new condominiums situated ...,370000,Studio / 1 Bath,405,-73.869225,40.724510,NaN,NaN,1.0
1821,Investor opportunity! This property is being ...,68743,NaN,960,-76.609010,39.230755,5653,NaN,1.0
1896,shopping center in hialeah 100% occupied very...,5250000,NaN,27225,-80.291420,25.864600,0.63,NaN,NaN
1903,NEW PRICE! The owner currently uses the lot a...,230000,NaN,2875,-122.201260,37.789400,2875,NaN,NaN
1917,Investor opportunity! This property is being ...,621941,NaN,1638,-73.864980,40.708890,3435,NaN,NaN
1927,Top floor studio apartment in the heart of Ca...,166700,Studio / 1 Bath,294,-104.973780,39.732277,358,NaN,1.0